name: Download JEPX data

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Determine date
        run: |
          DAY=$(date -u -d 'yesterday' '+%Y/%m/%d')
          NO_SLASH=$(date -u -d 'yesterday' '+%Y%m%d')
          YEAR=$(date -u -d 'yesterday' '+%Y')
          echo "SCRAPE_DATE=$DAY" >> "$GITHUB_ENV"
          echo "DAY_NOSLASH=$NO_SLASH" >> "$GITHUB_ENV"
          echo "YEAR=$YEAR" >> "$GITHUB_ENV"

      - name: Run scraper
        run: python run_jepx_curve.py "$SCRAPE_DATE"

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jepx-${{ env.DAY_NOSLASH }}
          path: |
            csv/${{ env.YEAR }}/spot_bid_curves_${{ env.DAY_NOSLASH }}.csv
            csv/${{ env.YEAR }}/spot_splitting_areas_${{ env.DAY_NOSLASH }}.csv
          if-no-files-found: ignore
