name: Download JEPX data

on:
  schedule:
    - cron: '30 1 * * *'  # JST 10:30
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper (auto-select date by JST)
        run: python run_jepx_curve.py

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jepx-latest
          path: |
            csv/**/*.csv
          if-no-files-found: ignore
