name: Download JEPX data

on:
  schedule:
    - cron: '30 1 * * *'  # JST 10:30 every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Calculate JST target date
        id: jst_date
        run: |
          TZ=Asia/Tokyo
          HOUR=$(date +'%H' --date='TZ="Asia/Tokyo"')
          MINUTE=$(date +'%M' --date='TZ="Asia/Tokyo"')
          if [ "$HOUR" -lt 10 ] || { [ "$HOUR" -eq 10 ] && [ "$MINUTE" -lt 30 ]; }; then
            TARGET_DATE=$(date +'%Y/%m/%d' --date='TZ="Asia/Tokyo"')
          else
            TARGET_DATE=$(date +'%Y/%m/%d' --date='TZ="Asia/Tokyo" +1 day')
          fi

          TARGET_DATE_SLUG=${TARGET_DATE////-}
          TARGET_YEAR=$(echo $TARGET_DATE | cut -d'/' -f1)

          echo "TARGET_DATE=$TARGET_DATE" >> "$GITHUB_ENV"
          echo "TARGET_DATE_SLUG=$TARGET_DATE_SLUG" >> "$GITHUB_ENV"
          echo "TARGET_YEAR=$TARGET_YEAR" >> "$GITHUB_ENV"
          echo "Target date: $TARGET_DATE (slug: $TARGET_DATE_SLUG)"
      
      - name: Run spot curve scraper
        run: python run_jepx_curve.py "$TARGET_DATE"

      - name: Run spot summary scraper
        run: python run_jepx_summary.py "$TARGET_DATE"

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jepx-${{ env.TARGET_DATE_SLUG }}
          path: |
            csv/${{ env.TARGET_YEAR }}/spot_bid_curves_${{ env.TARGET_DATE_SLUG }}.csv
            csv/${{ env.TARGET_YEAR }}/spot_splitting_areas_${{ env.TARGET_DATE_SLUG }}.csv
            csv/spot_summary_${{ env.TARGET_YEAR }}.csv
          if-no-files-found: ignore
